# Server port
server.port=8761

# This is a standalone Eureka server (doesn't register itself)
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

## ? Disable self-preservation in DEV so Eureka evicts dead instances quickly
#eureka.server.enable-self-preservation=false
#
## Run eviction every 5s (default is 60s)
#eureka.server.eviction-interval-timer-in-ms=5000
